# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/octo/CLionProjects/WIMY

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/octo/CLionProjects/WIMY/build-windows

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/octo/CLionProjects/WIMY/build-windows/CMakeFiles /home/octo/CLionProjects/WIMY/build-windows//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/octo/CLionProjects/WIMY/build-windows/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/octo/CLionProjects/WIMY/build-windows/CMakeFiles /home/octo/CLionProjects/WIMY/build-windows//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/octo/CLionProjects/WIMY/build-windows/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WIMY

# Build rule for target.
WIMY: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WIMY
.PHONY : WIMY

# fast build rule for target.
WIMY/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/build
.PHONY : WIMY/fast

#=============================================================================
# Target rules for targets named r3d

# Build rule for target.
r3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r3d
.PHONY : r3d

# fast build rule for target.
r3d/fast:
	$(MAKE) $(MAKESILENT) -f _deps/r3d-build/CMakeFiles/r3d.dir/build.make _deps/r3d-build/CMakeFiles/r3d.dir/build
.PHONY : r3d/fast

#=============================================================================
# Target rules for targets named r3d_shaders

# Build rule for target.
r3d_shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r3d_shaders
.PHONY : r3d_shaders

# fast build rule for target.
r3d_shaders/fast:
	$(MAKE) $(MAKESILENT) -f _deps/r3d-build/CMakeFiles/r3d_shaders.dir/build.make _deps/r3d-build/CMakeFiles/r3d_shaders.dir/build
.PHONY : r3d_shaders/fast

#=============================================================================
# Target rules for targets named r3d_assets

# Build rule for target.
r3d_assets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r3d_assets
.PHONY : r3d_assets

# fast build rule for target.
r3d_assets/fast:
	$(MAKE) $(MAKESILENT) -f _deps/r3d-build/CMakeFiles/r3d_assets.dir/build.make _deps/r3d-build/CMakeFiles/r3d_assets.dir/build
.PHONY : r3d_assets/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) $(MAKESILENT) -f _deps/r3d-build/external/assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build.make _deps/r3d-build/external/assimp/contrib/zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/r3d-build/external/assimp/code/CMakeFiles/assimp.dir/build.make _deps/r3d-build/external/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/r3d-build/external/raylib/CMakeFiles/uninstall.dir/build.make _deps/r3d-build/external/raylib/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/r3d-build/external/raylib/raylib/CMakeFiles/raylib.dir/build.make _deps/r3d-build/external/raylib/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/r3d-build/external/raylib/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make _deps/r3d-build/external/raylib/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/r3d-build/external/raylib/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make _deps/r3d-build/external/raylib/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

BackSystem.obj: BackSystem.cpp.obj
.PHONY : BackSystem.obj

# target to build an object file
BackSystem.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/BackSystem.cpp.obj
.PHONY : BackSystem.cpp.obj

BackSystem.i: BackSystem.cpp.i
.PHONY : BackSystem.i

# target to preprocess a source file
BackSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/BackSystem.cpp.i
.PHONY : BackSystem.cpp.i

BackSystem.s: BackSystem.cpp.s
.PHONY : BackSystem.s

# target to generate assembly for a file
BackSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/BackSystem.cpp.s
.PHONY : BackSystem.cpp.s

Camera.obj: Camera.cpp.obj
.PHONY : Camera.obj

# target to build an object file
Camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/Camera.cpp.obj
.PHONY : Camera.cpp.obj

Camera.i: Camera.cpp.i
.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s
.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

ConnectSystem.obj: ConnectSystem.cpp.obj
.PHONY : ConnectSystem.obj

# target to build an object file
ConnectSystem.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/ConnectSystem.cpp.obj
.PHONY : ConnectSystem.cpp.obj

ConnectSystem.i: ConnectSystem.cpp.i
.PHONY : ConnectSystem.i

# target to preprocess a source file
ConnectSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/ConnectSystem.cpp.i
.PHONY : ConnectSystem.cpp.i

ConnectSystem.s: ConnectSystem.cpp.s
.PHONY : ConnectSystem.s

# target to generate assembly for a file
ConnectSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/ConnectSystem.cpp.s
.PHONY : ConnectSystem.cpp.s

Listener.obj: Listener.cpp.obj
.PHONY : Listener.obj

# target to build an object file
Listener.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/Listener.cpp.obj
.PHONY : Listener.cpp.obj

Listener.i: Listener.cpp.i
.PHONY : Listener.i

# target to preprocess a source file
Listener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/Listener.cpp.i
.PHONY : Listener.cpp.i

Listener.s: Listener.cpp.s
.PHONY : Listener.s

# target to generate assembly for a file
Listener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/Listener.cpp.s
.PHONY : Listener.cpp.s

UIManager.obj: UIManager.cpp.obj
.PHONY : UIManager.obj

# target to build an object file
UIManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/UIManager.cpp.obj
.PHONY : UIManager.cpp.obj

UIManager.i: UIManager.cpp.i
.PHONY : UIManager.i

# target to preprocess a source file
UIManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/UIManager.cpp.i
.PHONY : UIManager.cpp.i

UIManager.s: UIManager.cpp.s
.PHONY : UIManager.s

# target to generate assembly for a file
UIManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/UIManager.cpp.s
.PHONY : UIManager.cpp.s

UnitManager.obj: UnitManager.cpp.obj
.PHONY : UnitManager.obj

# target to build an object file
UnitManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/UnitManager.cpp.obj
.PHONY : UnitManager.cpp.obj

UnitManager.i: UnitManager.cpp.i
.PHONY : UnitManager.i

# target to preprocess a source file
UnitManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/UnitManager.cpp.i
.PHONY : UnitManager.cpp.i

UnitManager.s: UnitManager.cpp.s
.PHONY : UnitManager.s

# target to generate assembly for a file
UnitManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/UnitManager.cpp.s
.PHONY : UnitManager.cpp.s

cycles/CycleToCycle.obj: cycles/CycleToCycle.cpp.obj
.PHONY : cycles/CycleToCycle.obj

# target to build an object file
cycles/CycleToCycle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/CycleToCycle.cpp.obj
.PHONY : cycles/CycleToCycle.cpp.obj

cycles/CycleToCycle.i: cycles/CycleToCycle.cpp.i
.PHONY : cycles/CycleToCycle.i

# target to preprocess a source file
cycles/CycleToCycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/CycleToCycle.cpp.i
.PHONY : cycles/CycleToCycle.cpp.i

cycles/CycleToCycle.s: cycles/CycleToCycle.cpp.s
.PHONY : cycles/CycleToCycle.s

# target to generate assembly for a file
cycles/CycleToCycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/CycleToCycle.cpp.s
.PHONY : cycles/CycleToCycle.cpp.s

cycles/DistributionCycle.obj: cycles/DistributionCycle.cpp.obj
.PHONY : cycles/DistributionCycle.obj

# target to build an object file
cycles/DistributionCycle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/DistributionCycle.cpp.obj
.PHONY : cycles/DistributionCycle.cpp.obj

cycles/DistributionCycle.i: cycles/DistributionCycle.cpp.i
.PHONY : cycles/DistributionCycle.i

# target to preprocess a source file
cycles/DistributionCycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/DistributionCycle.cpp.i
.PHONY : cycles/DistributionCycle.cpp.i

cycles/DistributionCycle.s: cycles/DistributionCycle.cpp.s
.PHONY : cycles/DistributionCycle.s

# target to generate assembly for a file
cycles/DistributionCycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/DistributionCycle.cpp.s
.PHONY : cycles/DistributionCycle.cpp.s

cycles/EventCycle.obj: cycles/EventCycle.cpp.obj
.PHONY : cycles/EventCycle.obj

# target to build an object file
cycles/EventCycle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/EventCycle.cpp.obj
.PHONY : cycles/EventCycle.cpp.obj

cycles/EventCycle.i: cycles/EventCycle.cpp.i
.PHONY : cycles/EventCycle.i

# target to preprocess a source file
cycles/EventCycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/EventCycle.cpp.i
.PHONY : cycles/EventCycle.cpp.i

cycles/EventCycle.s: cycles/EventCycle.cpp.s
.PHONY : cycles/EventCycle.s

# target to generate assembly for a file
cycles/EventCycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/EventCycle.cpp.s
.PHONY : cycles/EventCycle.cpp.s

cycles/PhysicsCycle.obj: cycles/PhysicsCycle.cpp.obj
.PHONY : cycles/PhysicsCycle.obj

# target to build an object file
cycles/PhysicsCycle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/PhysicsCycle.cpp.obj
.PHONY : cycles/PhysicsCycle.cpp.obj

cycles/PhysicsCycle.i: cycles/PhysicsCycle.cpp.i
.PHONY : cycles/PhysicsCycle.i

# target to preprocess a source file
cycles/PhysicsCycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/PhysicsCycle.cpp.i
.PHONY : cycles/PhysicsCycle.cpp.i

cycles/PhysicsCycle.s: cycles/PhysicsCycle.cpp.s
.PHONY : cycles/PhysicsCycle.s

# target to generate assembly for a file
cycles/PhysicsCycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/PhysicsCycle.cpp.s
.PHONY : cycles/PhysicsCycle.cpp.s

cycles/RenderCycle.obj: cycles/RenderCycle.cpp.obj
.PHONY : cycles/RenderCycle.obj

# target to build an object file
cycles/RenderCycle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/RenderCycle.cpp.obj
.PHONY : cycles/RenderCycle.cpp.obj

cycles/RenderCycle.i: cycles/RenderCycle.cpp.i
.PHONY : cycles/RenderCycle.i

# target to preprocess a source file
cycles/RenderCycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/RenderCycle.cpp.i
.PHONY : cycles/RenderCycle.cpp.i

cycles/RenderCycle.s: cycles/RenderCycle.cpp.s
.PHONY : cycles/RenderCycle.s

# target to generate assembly for a file
cycles/RenderCycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/RenderCycle.cpp.s
.PHONY : cycles/RenderCycle.cpp.s

cycles/StatusCycle.obj: cycles/StatusCycle.cpp.obj
.PHONY : cycles/StatusCycle.obj

# target to build an object file
cycles/StatusCycle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/StatusCycle.cpp.obj
.PHONY : cycles/StatusCycle.cpp.obj

cycles/StatusCycle.i: cycles/StatusCycle.cpp.i
.PHONY : cycles/StatusCycle.i

# target to preprocess a source file
cycles/StatusCycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/StatusCycle.cpp.i
.PHONY : cycles/StatusCycle.cpp.i

cycles/StatusCycle.s: cycles/StatusCycle.cpp.s
.PHONY : cycles/StatusCycle.s

# target to generate assembly for a file
cycles/StatusCycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/StatusCycle.cpp.s
.PHONY : cycles/StatusCycle.cpp.s

cycles/SyncCycle.obj: cycles/SyncCycle.cpp.obj
.PHONY : cycles/SyncCycle.obj

# target to build an object file
cycles/SyncCycle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/SyncCycle.cpp.obj
.PHONY : cycles/SyncCycle.cpp.obj

cycles/SyncCycle.i: cycles/SyncCycle.cpp.i
.PHONY : cycles/SyncCycle.i

# target to preprocess a source file
cycles/SyncCycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/SyncCycle.cpp.i
.PHONY : cycles/SyncCycle.cpp.i

cycles/SyncCycle.s: cycles/SyncCycle.cpp.s
.PHONY : cycles/SyncCycle.s

# target to generate assembly for a file
cycles/SyncCycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/SyncCycle.cpp.s
.PHONY : cycles/SyncCycle.cpp.s

cycles/UIRenderCycle.obj: cycles/UIRenderCycle.cpp.obj
.PHONY : cycles/UIRenderCycle.obj

# target to build an object file
cycles/UIRenderCycle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/UIRenderCycle.cpp.obj
.PHONY : cycles/UIRenderCycle.cpp.obj

cycles/UIRenderCycle.i: cycles/UIRenderCycle.cpp.i
.PHONY : cycles/UIRenderCycle.i

# target to preprocess a source file
cycles/UIRenderCycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/UIRenderCycle.cpp.i
.PHONY : cycles/UIRenderCycle.cpp.i

cycles/UIRenderCycle.s: cycles/UIRenderCycle.cpp.s
.PHONY : cycles/UIRenderCycle.s

# target to generate assembly for a file
cycles/UIRenderCycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/cycles/UIRenderCycle.cpp.s
.PHONY : cycles/UIRenderCycle.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WIMY.dir/build.make CMakeFiles/WIMY.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... r3d_assets"
	@echo "... r3d_shaders"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... WIMY"
	@echo "... assimp"
	@echo "... glfw"
	@echo "... r3d"
	@echo "... raylib"
	@echo "... zlibstatic"
	@echo "... BackSystem.obj"
	@echo "... BackSystem.i"
	@echo "... BackSystem.s"
	@echo "... Camera.obj"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... ConnectSystem.obj"
	@echo "... ConnectSystem.i"
	@echo "... ConnectSystem.s"
	@echo "... Listener.obj"
	@echo "... Listener.i"
	@echo "... Listener.s"
	@echo "... UIManager.obj"
	@echo "... UIManager.i"
	@echo "... UIManager.s"
	@echo "... UnitManager.obj"
	@echo "... UnitManager.i"
	@echo "... UnitManager.s"
	@echo "... cycles/CycleToCycle.obj"
	@echo "... cycles/CycleToCycle.i"
	@echo "... cycles/CycleToCycle.s"
	@echo "... cycles/DistributionCycle.obj"
	@echo "... cycles/DistributionCycle.i"
	@echo "... cycles/DistributionCycle.s"
	@echo "... cycles/EventCycle.obj"
	@echo "... cycles/EventCycle.i"
	@echo "... cycles/EventCycle.s"
	@echo "... cycles/PhysicsCycle.obj"
	@echo "... cycles/PhysicsCycle.i"
	@echo "... cycles/PhysicsCycle.s"
	@echo "... cycles/RenderCycle.obj"
	@echo "... cycles/RenderCycle.i"
	@echo "... cycles/RenderCycle.s"
	@echo "... cycles/StatusCycle.obj"
	@echo "... cycles/StatusCycle.i"
	@echo "... cycles/StatusCycle.s"
	@echo "... cycles/SyncCycle.obj"
	@echo "... cycles/SyncCycle.i"
	@echo "... cycles/SyncCycle.s"
	@echo "... cycles/UIRenderCycle.obj"
	@echo "... cycles/UIRenderCycle.i"
	@echo "... cycles/UIRenderCycle.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

